version: '3.8'

services:
  db:
    image: postgres:16
    container_name: conectadoacoes
    environment:
      POSTGRES_DB: conectadoacoes
      POSTGRES_USER: gui
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
